### ISSUE TITLE
Gradle link  broken

### ISSUE THREAD

**Issue by younes0** [polok/TaggerString#6]
could you confirm this please?
I've tried:

```
compile 'com.github.polok.taggerstring:taggerstring:1.1.0'
compile 'com.github.polok.taggerstring:taggerstring:1.0.0'
compile 'com.github.polok.taggerstring:1.0.0'
compile 'com.github.polok.taggerstring:library:1.1.0'
```

**Comment by younes0** [comment]
this one works: compile 'com.github.polok.taggerstring:library:1.0.0'

**Comment by polok** [comment]
Hi,

Thanks a lot for this one. Should be fine in few hours (Maven central sync).

2015-01-20 11:20 GMT+01:00 Younès <notifications@github.com>:

> this one works: compile 'com.github.polok.taggerstring:library:1.0.0'
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/polok/TaggerString/issues/6#issuecomment-70632571>.
>



-- 
Pozdrawiam,

Marcin Polak
